apiVersion: v1
kind: Service
metadata:
  name: lb-service
  namespace: default  # Change this if your app is in a different namespace
spec:
  type: LoadBalancer
  selector:
    app: lb-app  # Make sure this matches your app's pod labels
  ports:
    - port: 80       # Port your app is listening on
      targetPort: 8080  # Port on which your app container is listening
